### ISSUE TITLE
Incorrectly parses \\ in templates.

### ISSUE THREAD

**Issue by shadowmint** [sunng87/handlebars-rust#216]
The template:

    {{FOO}} {{BAR}} {{FOO}}{{BAR}} {{FOO}}#{{BAR}} {{FOO}}//{{BAR}} {{FOO}}\\{{FOO}} {{FOO}}\\\\{{FOO}}\\\\{{FOO}}

Renders:

    foo bar foobar foo#bar foo//bar foo\\{{FOO}} foo{{FOO}}{{FOO}}

I have been looking through the handlebars spec regarding `\`, but I can't see anything specific about this in it; it seems like a bug.

Note that other various character variations, eg. "{{FOO}}xxxx{{BAR}}" are fine, it's just for `\`.

This tangibly manifests itself as a bug when rendering windows paths in templates, eg:

    {{BUILD_PATH}}\{{PROJECT_FOLDER_XXX}}
    Invalid template, ""while parsing a quoted scalar, found unknown escape character"

but: 

    {{BUILD_PATH}}\\{{PROJECT_FOLDER_XXX}}
    renders: C:\projects\builds\source\artifacts\{{PROJECT_FOLDER_XXX}}

^ --- This is very surprising, and I'm pretty sure, not the correct behavior.

**Comment by sunng87** [comment]
There is escaping rules for handlebars:

when `{"foo": "bar"}` we will have
```
\{{foo}} => {{foo}}
\\{{foo}} => \bar
\\\\{{foo}} => \\\bar
```

The current implementation in handlebars-rust has issue with handling `\\`. I'm looking into the parser to see how to support that.

**Comment by sunng87** [comment]
@shadowmint this should have been fixed in #217. I'll create a release soon

**Comment by shadowmint** [comment]
Hm... the issue I was having before is indeed fixed, but I'm still seeing strange results in various edge cases:

Cargo.toml:
```
[package]
name = "temp"
version = "0.1.0"
authors = ["doug>"]

[dependencies]
handlebars = "1.0.0-beta.2"
serde_json = "*"
```

main.rs:
```
extern crate handlebars;

#[macro_use]
extern crate serde_json;

use handlebars::Handlebars;

fn main() {
    let mut reg = Handlebars::new();
    println!("{}", reg.render_template(r"foo\{{bar}}", &json!({"foo": "foo", "bar": "bar"})).unwrap());
    println!("{}", reg.render_template(r"{{foo}}\bar", &json!({"foo": "foo", "bar": "bar"})).unwrap());
    println!("{}", reg.render_template(r"{{foo}}\{{bar}}", &json!({"foo": "foo", "bar": "bar"})).unwrap());
    println!("{}", reg.render_template(r"{{foo}}\{{bar}}\", &json!({"foo": "foo", "bar": "bar"})).unwrap());
    println!("{}", reg.render_template(r"{{foo}}\hello\{{bar}}\", &json!({"foo": "foo", "bar": "bar"})).unwrap());
    println!("{}", reg.render_template(r"{{foo}}\hello\{{bar}}", &json!({"foo": "foo", "bar": "bar"})).unwrap());
}
```

Output:
```
   Compiling temp v0.1.0 
    Finished dev [unoptimized + debuginfo] target(s) in 2.94 secs
     Running `C:\projects\builds\tasks\steps\config\generateLicence\versions\0.1.0\temp\target\debug\temp.exe`
foo{{bar}}
foo\bar
foo{{bar}}
foo{{bar}}\
foo\hello{{bar}}\
foo\hello{{bar}}
```

**Comment by sunng87** [comment]
@shadowmint could you please point out which output is incorrect? I just verified against http://tryhandlebarsjs.com/ it seems the behaviour has been consistent with handlebars.js

**Comment by sunng87** [comment]
![image](https://user-images.githubusercontent.com/221942/41187855-ce5f8728-6be5-11e8-8062-0a60e7bf0e94.png)


I have `{{foo}}\hello\{{bar}}\` rendered `foo\hello\{{bar}}\` on tryhandlebarsjs.com. Did I miss anything?

The backslash after `hello` escapes `{{bar}}` so it's not rendered.

**Comment by shadowmint** [comment]
Ah, my mistake, I was looking at the rendered output from mustache, not handlebars when it renders that output.

I guess you can leave this closed then... I'll just leave this here for anyone else who finds this issue later:

If you want to render `\foo` from a template, the template form your require is `\\{{prop}}`; this isn't documented anywhere meaningfully, but `\{{...}}' is a handlebars inline escape sequence; by adding an additional \ prefix, it is no longer treated as an inline escape and instead renders as a \.

See this test suite in the handlebars.js repo: https://github.com/wycats/handlebars.js/blob/master/spec/tokenizer.js#L80

ie. What I need was a template like this:

    println!("{}", reg.render_template(r"{{foo}}\hello\\{{bar}}\", &json!({"foo": "foo", "bar": "bar"})).unwrap());
